### PR TITLE
Add Firefox support

### PR DESCRIPTION
**Pull request by cycool29**
Found a way from [Webapp-manager](https://github.com/linuxmint/webapp-manager/) to add firefox support like this:

```
sh -c 'XAPP_FORCE_GTKWINDOW_ICON={icon file} firefox --class Zoom-PWA --profile {config/profile folder} --no-remote http://pwa.zoom.us/wc'
```

Still working, just create this PR to keep track. 

Known bugs:
- Often crash during meeting
- Window title ends with ` - Firefox` (not big deal, just want to be nice)

Currently busy with my [shooting-game](https://github.com/cycool29/shooting-game) project. @Botspot If you have time, you may try to complete the install script (just make `if` `else` statement for chromium and firefox).

### CODE REVIEW

**Comment by cycool29** [comment]
@Botspot The script finally works now. But Firefox version often crash, unable to create a new meeting (sometimes not even able join a meeting), user needs to sign in everytime launch, mic and camera often not working.

image


Why not use nativefier? I tried to build with just `nativefier -a $(uname -m) https://pwa.zoom.us/wc` and everything works well.

**Comment by Botspot** [comment]
> @Botspot The script finally works now. But Firefox version often crash

Well that's too bad.

> Why not use nativefier? I tried to build with just `nativefier -a $(uname -m) https://pwa.zoom.us/wc` and everything works well.

I initially started with nativefier, and while it worked *fine*, Chromium seemed to be a tiny bit faster during meetings. And this makes sense - Chromium has some RPi-specific optimizations.
Should this PR be closed?

**Comment by cycool29** [comment]
> Should this PR be closed?

Not so fast. Maybe we can use nativefier version if chromium is not installed?

**Comment by cycool29** [comment]
Closing, since I think Chromium will be better than nativefier.

**Pull request closed without merging**
